server:
  port: ${PORT:8080}
spring:
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

  sleuth:
    sampler:
      rate: 1000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
