spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/bookstore-realm

logging.level:
  org.springframework.security: debug

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
