server:
  port: ${PORT:7777}

spring:

  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

#security.oauth2.resource.userInfoUri=http://localhost:7878/uaa/user
