server:
  port: ${PORT:7777}

spring:

  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
    instances:
      titles:
        baseConfig: default
        waitDurationInOpenState: 90s
      titles-annotated:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
      titles-annotated:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      titles:
        baseConfig: default
      titles-annotated:
        baseConfig: titles-annotated

#security.oauth2.resource.userInfoUri=http://localhost:7878/uaa/user
