spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOCK_SERVER_URL:http://localhost:9080}/realms/bookstore

bookstore:
  circuitbreaker:
    configuration:
      enabled: true
      circuitbreaker:
        configs:
          default:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
        instances:
          titles:
            baseConfig: default
            waitDurationInOpenState: 90s
          titles-another:
            baseConfig: default
      timelimiter:
        configs:
          default:
            timeoutDuration: 3s
            cancelRunningFuture: true
          titles-another:
            timeoutDuration: 2s
            cancelRunningFuture: true
        instances:
          titles:
            baseConfig: default
          titles-another:
            baseConfig: titles-another

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
    instances:
      titles-annotated:
        baseConfig: default
      titles-annotated-another:
        baseConfig: default
        waitDurationInOpenState: 90s

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
      titles-annotated:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      titles-annotated:
        baseConfig: titles-annotated
      titles-annotated-another:
        baseConfig: default

#security.oauth2.resource.userInfoUri=http://localhost:7878/uaa/user
