server:
  port: ${PORT:8000}

#eureka.client.serviceUrl.defaultZone=${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

spring:

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        fail-fast: true
      config:
        enabled: false
      retry:
        initial-interval: 1000
        max-attempts: 10
        max-interval: 60000
        multiplier: 1.2

  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
