spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: hello-service
          uri: lb://hello-service
          predicates:
            - Path=/hello-service/**
          filters:
            - RewritePath=/hello-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: hello-service
                fallbackUri: forward:/fallback
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
          filters:
            - RewritePath=/book-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: book-service
                fallbackUri: forward:/fallback
        - id: bookstore-client
          uri: lb://bookstore-client
          predicates:
            - Path=/bookstore-client/**
          filters:
            - RewritePath=/bookstore-client/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: bookstore-client
                fallbackUri: forward:/fallback

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookstore-client
            client-secret: 1Wv1v7zOxy82GH5bSKl7DrVVGe5AKTET
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: ${KEYCLOCK_SERVER_URL:http://localhost:9080}/realms/bookstore/protocol/openid-connect/auth
            token-uri: ${KEYCLOCK_SERVER_URL:http://localhost:9080}/realms/bookstore/protocol/openid-connect/token
            user-info-uri: ${KEYCLOCK_SERVER_URL:http://localhost:9080}/realms/bookstore/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOCK_SERVER_URL:http://localhost:9080}/realms/bookstore/protocol/openid-connect/certs
            issuer-uri: ${KEYCLOCK_SERVER_URL:http://localhost:9080}/realms/bookstore
            user-name-attribute: preferred_username

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
    instances:
      hello-service:
        baseConfig: default
      book-service:
        baseConfig: default
      bookstore-client:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      hello-service:
        baseConfig: default
      book-service:
        baseConfig: default
      bookstore-client:
        baseConfig: default

logging.level:
  org.springframework.cloud.gateway: trace
  org.springframework.http.server.reactive: DEBUG
  org.springframework.web.reactive: DEBUG
