server:
  port: ${PORT:8000}

spring:
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

message: Hello world 555!
hello-world:
  message: Hello world 2!
encrypted-message: '{cipher}AgByGE0LRAy0G768/8ieDODRMsPRVyIm/XqJCG+h9308OT9Ju6DqcbLv2zbsWrDglkyHCm6Mxwu+SS/OWO3rSYWepOSJcnOE+YtAH4eYNi1TtObMBV1ZDjVtPVGNcJk7rDFNs/vDBL+YFhCKb9r9xVP1chlZ6ApiXfVc/+DYFDjAlrTTOK9XlFk1dd1S57WuKCoVpo/UcKxwSJdsIfk59yki8jfqu/gKYGnUB/N/QVv49SOvVLUccNYrfCiM/Laz7JiniDG8we0jUKGJismmDFFT41cTzVHucWqpN0ID7bkKwEA8knIdlRKgCSrF75JMmTCOCdkkDpHVYvqJ3Z4f1a6BRoCjOWXeiHVtgkZgvcNNIadmMLmwsPmQsDRtX+CHjEfx0TiZoBBPJr8vOk5mn2MTldTl6gyhe6CUWpR1+aC621avEoHUZe5tCA4+W0jUqJ69sEKHYL9/zcLwArf7ukgdX3cfIr9XgTwdLfnGIkbFQoF66o95tBiMTxLhlZrDTzEzjLtqYPKNb/NVQnMSZO74Jtaj+2n8NjQ/acaE3D/1PDEKrL78GCPB+aS4UVoSJXNJ4XFHIhbl2k7ez1h6wGsnqFgn4fi474s1kSsNlEeCxOQfxdr8UYV9IUC4dQt/JvwX++uxl/5k+2YD3dv6m1HjwOHt3cIETdwYhSXQabwpRjnn3RqrFx6cfq928zegwF7e2598tpK2uEniCQWS0Pk5HdEEofx+h3eFv5HfpUQMXTygPEYRLWh68OndDsWkjPI='
